begin;

-- Journal entry numbers continue a Discord history that predates this website,
-- so hosts are invited to type a known number ("Leave blank for the next
-- number. Change it only to correct an entry."). journal_entries.entry_number
-- is `generated by default as identity`, which means an explicitly supplied
-- value does NOT advance the underlying sequence. The next automatically
-- numbered entry therefore reuses a number that already exists and fails the
-- (group_id, entry_number) unique constraint, permanently breaking Journal
-- saving with a raw Postgres error.
--
-- This migration keeps the sequence ahead of the data and replaces the raw
-- constraint error with a message that says what to do about it.

-- ---------------------------------------------------------------- sequence repair
-- setval requires UPDATE on the sequence, which `authenticated` deliberately
-- does not hold, so the helper is security definer and takes no arguments: it
-- can only ever move the sequence forward to the highest number already stored.
--
-- The sequence is global while the unique constraint is per group. Syncing to
-- the global maximum can skip numbers if a second group is ever added; that is
-- the safe direction, because a skipped number is harmless and a reused one is
-- not.
create or replace function private.sync_journal_entry_number_sequence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  highest bigint;
  current_last bigint;
  called boolean;
  next_value bigint;
begin
  select max(entry_number) into highest from public.journal_entries;

  -- No rows means the sequence must keep its untouched start value, otherwise
  -- the group's first entry would silently skip 1317.
  if highest is null then
    return;
  end if;

  -- pg_sequences.last_value reports NULL until the sequence is first used, so
  -- read the sequence relation directly and interpret is_called properly.
  select last_value, is_called
  into current_last, called
  from public.journal_entries_entry_number_seq;

  next_value := case when called then current_last + 1 else current_last end;

  -- Only ever move forward. Backfilling a low historical number must not drag
  -- the sequence back over numbers that are already in use.
  if highest >= next_value then
    perform setval('public.journal_entries_entry_number_seq', highest, true);
  end if;
end;
$$;

comment on function private.sync_journal_entry_number_sequence() is
  'Moves the journal_entries.entry_number identity sequence forward past any explicitly numbered entry. Never moves it backwards.';

revoke all on function private.sync_journal_entry_number_sequence() from public, anon;
grant execute on function private.sync_journal_entry_number_sequence() to authenticated;

-- ---------------------------------------------------------------- journal save
-- Unchanged from 20260823214112 except for the duplicate-number pre-check, the
-- unique_violation handler and the two sequence-sync calls.
create or replace function public.save_movie_session_journal(
  p_session_id uuid,
  p_title text,
  p_release_year integer,
  p_status text,
  p_comment text,
  p_entry_number bigint default null
)
returns public.journal_entries
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target public.movie_sessions;
  saved public.journal_entries;
  viewer_names text;
begin
  if (select auth.uid()) is null then
    raise exception 'Sign in to save a Journal entry.';
  end if;

  select * into target
  from public.movie_sessions
  where id = p_session_id;

  if target.id is null then
    raise exception 'That session does not exist, or you cannot view it.';
  end if;

  if target.status <> 'WATCHED' then
    raise exception 'The Journal becomes available after the film is marked watched.';
  end if;

  if not (
    target.host_id = (select auth.uid())
    or private.is_group_admin(target.group_id)
  ) then
    raise exception 'Only the session host or a website administrator can save this Journal entry.';
  end if;

  if nullif(trim(p_title), '') is null then
    raise exception 'Enter a Journal title.';
  end if;

  if upper(p_status) not in ('FINISHED', 'DNF') then
    raise exception 'Journal status must be Finished or DNF.';
  end if;

  if p_entry_number is not null and p_entry_number < 1 then
    raise exception 'Entry number must be positive.';
  end if;

  if not exists (
    select 1
    from public.movie_session_participants participant
    where participant.session_id = target.id
  ) then
    raise exception 'The watched session must have at least one participant.';
  end if;

  select string_agg(participant.display_name_snapshot, ', ' order by participant.added_at, participant.id)
  into viewer_names
  from public.movie_session_participants participant
  where participant.session_id = target.id;

  select * into saved
  from public.journal_entries
  where movie_session_id = p_session_id;

  -- Say which number is taken before Postgres reports a constraint name that
  -- the person typing a comment cannot act on.
  if p_entry_number is not null and exists (
    select 1
    from public.journal_entries existing
    where existing.group_id = target.group_id
      and existing.entry_number = p_entry_number
      and (saved.id is null or existing.id <> saved.id)
  ) then
    -- Deliberately the default raise_exception code, not unique_violation, so
    -- this does not fall into the handler at the end of the function.
    raise exception 'Journal entry #% already exists in this group. Leave the number blank for the next one, or choose a different number.', p_entry_number;
  end if;

  if saved.id is null then
    if p_entry_number is null then
      insert into public.journal_entries (
        group_id,
        movie_session_id,
        title,
        release_year,
        watched_at,
        status,
        comment,
        created_by
      ) values (
        target.group_id,
        target.id,
        trim(p_title),
        p_release_year,
        target.watch_date,
        upper(p_status),
        nullif(trim(p_comment), ''),
        (select auth.uid())
      )
      returning * into saved;
    else
      insert into public.journal_entries (
        group_id,
        movie_session_id,
        entry_number,
        title,
        release_year,
        watched_at,
        status,
        comment,
        created_by
      ) values (
        target.group_id,
        target.id,
        p_entry_number,
        trim(p_title),
        p_release_year,
        target.watch_date,
        upper(p_status),
        nullif(trim(p_comment), ''),
        (select auth.uid())
      )
      returning * into saved;

      -- An explicit number bypassed the identity default, so the sequence is
      -- behind the data until this runs.
      perform private.sync_journal_entry_number_sequence();
    end if;
  else
    update public.journal_entries
    set entry_number = coalesce(p_entry_number, entry_number),
        title = trim(p_title),
        release_year = p_release_year,
        watched_at = target.watch_date,
        status = upper(p_status),
        comment = nullif(trim(p_comment), '')
    where id = saved.id
    returning * into saved;

    if p_entry_number is not null then
      perform private.sync_journal_entry_number_sequence();
    end if;
  end if;

  delete from public.entry_viewers
  where entry_id = saved.id;

  insert into public.entry_viewers (entry_id, profile_id)
  select saved.id, participant.profile_id
  from public.movie_session_participants participant
  where participant.session_id = target.id
    and participant.profile_id is not null
  order by participant.added_at, participant.id;

  update public.movie_sessions
  set journal_draft = jsonb_build_object(
    'sessionId', target.id,
    'entryNumber', saved.entry_number::text,
    'title', saved.title,
    'year', coalesce(saved.release_year::text, ''),
    'viewerIds', coalesce((
      select jsonb_agg(participant.profile_id order by participant.added_at, participant.id)
      from public.movie_session_participants participant
      where participant.session_id = target.id
        and participant.profile_id is not null
    ), '[]'::jsonb),
    'viewers', coalesce(viewer_names, ''),
    'status', case when saved.status = 'DNF' then 'DNF' else 'Finished' end,
    'comment', coalesce(saved.comment, '')
  )
  where id = target.id;

  return saved;

exception
  -- Defence in depth: the pre-check above cannot see a number committed by a
  -- concurrent save between its SELECT and this INSERT.
  when unique_violation then
    if position('journal_entries_group_id_entry_number_key' in sqlerrm) > 0 then
      raise exception 'Journal entry #% already exists in this group. Leave the number blank for the next one, or choose a different number.', p_entry_number
        using errcode = 'unique_violation';
    end if;
    raise;
end;
$$;

revoke all on function public.save_movie_session_journal(uuid, text, integer, text, text, bigint) from public, anon;
grant execute on function public.save_movie_session_journal(uuid, text, integer, text, text, bigint) to authenticated;

-- Repair any drift this project already carries from before the fix.
select private.sync_journal_entry_number_sequence();

commit;
