begin;

create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.group_memberships (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('member', 'admin')),
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  entry_number bigint generated by default as identity (start with 1317),
  title text not null check (char_length(title) between 1 and 200),
  release_year integer check (release_year between 1888 and 2200),
  watched_at date not null default current_date,
  status text not null default 'FINISHED' check (status in ('FINISHED', 'DNF')),
  comment text check (comment is null or char_length(comment) <= 2000),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_id, entry_number)
);

create table public.entry_viewers (
  entry_id uuid not null references public.journal_entries(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  primary key (entry_id, profile_id)
);

create table public.queue_items (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  release_year integer check (release_year between 1888 and 2200),
  suggested_by uuid references public.profiles(id) on delete set null,
  watched boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.queue_votes (
  queue_item_id uuid not null references public.queue_items(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (queue_item_id, user_id)
);

create index group_memberships_user_id_idx on public.group_memberships(user_id);
create index journal_entries_group_watched_idx on public.journal_entries(group_id, watched_at desc, entry_number desc);
create index entry_viewers_profile_id_idx on public.entry_viewers(profile_id);
create index queue_items_group_watched_idx on public.queue_items(group_id, watched, created_at desc);
create index queue_votes_user_id_idx on public.queue_votes(user_id);

insert into public.groups (name, slug)
values ('The Discordians', 'the-discordians')
on conflict (slug) do update set name = excluded.name;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1), 'Discordian'), 40)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger journal_entries_set_updated_at
before update on public.journal_entries
for each row execute function private.set_updated_at();

create trigger queue_items_set_updated_at
before update on public.queue_items
for each row execute function private.set_updated_at();

create or replace function private.is_group_member(target_group uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.group_memberships membership
      where membership.group_id = target_group
        and membership.user_id = (select auth.uid())
    );
$$;

create or replace function private.is_group_admin(target_group uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.group_memberships membership
      where membership.group_id = target_group
        and membership.user_id = (select auth.uid())
        and membership.role = 'admin'
    );
$$;

create or replace function private.shares_group_with(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.group_memberships mine
      join public.group_memberships theirs on theirs.group_id = mine.group_id
      where mine.user_id = (select auth.uid())
        and theirs.user_id = target_user
    );
$$;

revoke all on function private.is_group_member(uuid) from public, anon, authenticated;
revoke all on function private.is_group_admin(uuid) from public, anon, authenticated;
revoke all on function private.shares_group_with(uuid) from public, anon, authenticated;

grant usage on schema private to authenticated;
grant execute on function private.is_group_member(uuid) to authenticated;
grant execute on function private.is_group_admin(uuid) to authenticated;
grant execute on function private.shares_group_with(uuid) to authenticated;

alter table public.groups enable row level security;
alter table public.profiles enable row level security;
alter table public.group_memberships enable row level security;
alter table public.journal_entries enable row level security;
alter table public.entry_viewers enable row level security;
alter table public.queue_items enable row level security;
alter table public.queue_votes enable row level security;

create policy groups_select_member
on public.groups for select
to authenticated
using (private.is_group_member(id));

create policy profiles_select_shared_group
on public.profiles for select
to authenticated
using (id = (select auth.uid()) or private.shares_group_with(id));

create policy profiles_update_self
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy memberships_select_group
on public.group_memberships for select
to authenticated
using (private.is_group_member(group_id));

create policy journal_entries_select_group
on public.journal_entries for select
to authenticated
using (private.is_group_member(group_id));

create policy journal_entries_insert_member
on public.journal_entries for insert
to authenticated
with check (
  private.is_group_member(group_id)
  and created_by = (select auth.uid())
);

create policy journal_entries_update_owner_or_admin
on public.journal_entries for update
to authenticated
using (created_by = (select auth.uid()) or private.is_group_admin(group_id))
with check (
  private.is_group_member(group_id)
  and (created_by = (select auth.uid()) or private.is_group_admin(group_id))
);

create policy journal_entries_delete_owner_or_admin
on public.journal_entries for delete
to authenticated
using (created_by = (select auth.uid()) or private.is_group_admin(group_id));

create policy entry_viewers_select_group
on public.entry_viewers for select
to authenticated
using (
  exists (
    select 1 from public.journal_entries entry
    where entry.id = entry_viewers.entry_id
      and private.is_group_member(entry.group_id)
  )
);

create policy entry_viewers_insert_owner_or_admin
on public.entry_viewers for insert
to authenticated
with check (
  exists (
    select 1 from public.journal_entries entry
    where entry.id = entry_viewers.entry_id
      and (entry.created_by = (select auth.uid()) or private.is_group_admin(entry.group_id))
  )
);

create policy entry_viewers_delete_owner_or_admin
on public.entry_viewers for delete
to authenticated
using (
  exists (
    select 1 from public.journal_entries entry
    where entry.id = entry_viewers.entry_id
      and (entry.created_by = (select auth.uid()) or private.is_group_admin(entry.group_id))
  )
);

create policy queue_items_select_group
on public.queue_items for select
to authenticated
using (private.is_group_member(group_id));

create policy queue_items_insert_member
on public.queue_items for insert
to authenticated
with check (
  private.is_group_member(group_id)
  and suggested_by = (select auth.uid())
);

create policy queue_items_update_owner_or_admin
on public.queue_items for update
to authenticated
using (suggested_by = (select auth.uid()) or private.is_group_admin(group_id))
with check (
  private.is_group_member(group_id)
  and (suggested_by = (select auth.uid()) or private.is_group_admin(group_id))
);

create policy queue_items_delete_owner_or_admin
on public.queue_items for delete
to authenticated
using (suggested_by = (select auth.uid()) or private.is_group_admin(group_id));

create policy queue_votes_select_group
on public.queue_votes for select
to authenticated
using (
  exists (
    select 1 from public.queue_items item
    where item.id = queue_votes.queue_item_id
      and private.is_group_member(item.group_id)
  )
);

create policy queue_votes_insert_self
on public.queue_votes for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.queue_items item
    where item.id = queue_votes.queue_item_id
      and private.is_group_member(item.group_id)
  )
);

create policy queue_votes_delete_self
on public.queue_votes for delete
to authenticated
using (user_id = (select auth.uid()));

revoke all on table public.groups from anon;
revoke all on table public.profiles from anon;
revoke all on table public.group_memberships from anon;
revoke all on table public.journal_entries from anon;
revoke all on table public.entry_viewers from anon;
revoke all on table public.queue_items from anon;
revoke all on table public.queue_votes from anon;

grant select on table public.groups to authenticated;
grant select, update on table public.profiles to authenticated;
grant select on table public.group_memberships to authenticated;
grant select, insert, update, delete on table public.journal_entries to authenticated;
grant select, insert, delete on table public.entry_viewers to authenticated;
grant select, insert, update, delete on table public.queue_items to authenticated;
grant select, insert, delete on table public.queue_votes to authenticated;
grant usage, select on sequence public.journal_entries_entry_number_seq to authenticated;

commit;
